### ISSUE TITLE
Cloud app updates other values than what was specified

### ISSUE THREAD

**Issue by martinpatrick** [ExLibrisGroup/alma-e-collection-quick-update#12]
Hello,

I ran the app in our Sandbox on 50 e-collections only to append something to the internal description field and have a few issues to report from one run of the app, which I'll try to separate into different issues. 

First up, the history of at least several collections that did update shows that the app changed two values (it updated the internal description field AND something else). I have not looked at every collection from the set. But, in one case it set the proxy enabled value, in another it set the CDI activation value, and in another I looked at it set the free/not free value. None of those were things I asked it to do.

Thanks!
Martin Patrick (University of Minnesota)

**Comment by jweisman** [comment]
Hi @martinpatrick . Thanks for your bug report. 

We'll look into it.

**Comment by ori229** [comment]
Hi Martin,
The Cloud App uses the REST APIs to update the e-collections. In order to troubleshoot the issue here, I would like to get your permission to update a few collections on your Sandbox Alma. I'll run a GET request and then PUT with the same payload as retrieved with GET, and verify that nothing has changed (no indication in the History/Audit tab).
Can you provide a few IDs for e-collection I can try that on?
Thanks,
Ori
Alma APIs team

**Comment by martinpatrick** [comment]
Hi Ori, 

Here's some IDs you can run against:
61535209460001701
61549770130001701
61542638630001701

Thanks!
Martin

**Comment by ori229** [comment]
Hi Martin,
We have found issues when running GET/PUT on 61549770130001701 & 61542638630001701
As you understand, the bug is with the APIs and not with the Cloud App.
We'll try to get it fixed for Alma's May Release.
Thanks,
Ori

**Comment by ulrikkeo** [comment]
Hi,

We've just experienced the same issue at the University of Oslo. We update collections to add a public note and our Proxy was removed. Any updates on when this might be resolved?

Kind regards, 
Ulrikke Greve Olufsen (Electronic Resources Librarian)

**Comment by jweisman** [comment]
Hi @ulrikkeo - thanks for your note. This issue was resolved in May 2021. I am therefore closing the issue.

I checked and confirmed that updating the public note doesn't not update the proxy fields- see the history screen below:
![Screen Shot 2022-01-30 at 12 31 09 ](https://user-images.githubusercontent.com/80420/151696082-373baccb-34ba-4647-99d3-5589de555613.png)

Perhaps the selected proxy is no longer valid and is therefore removed? If you're sure that's not the case, please open a new issue with the institution/environment you're checking in and on which collection, and we can take a look.
